default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 27.118.16.127
  username: haugreek
  password: jGc7w$93
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: haugreek

test:
  <<: *default
  database: haugreek

production:
  <<: *default
  database: haugreek
